#!/bin/bash
#To use the new features provided in this GRUB update, it is recommended
#to install it to the MBR or UEFI. Due to potential configuration
#incompatibilities, it is advised to run both, installation and generation
#of configuration:
# Updates grub
sudo grub-install --no-nvram
sudo grub-mkconfig -o /boot/grub/grub.cfg
